### ISSUE TITLE
你的请求那些都没有日志呢，有空可以加上吧

### ISSUE THREAD

**Issue by kwg520** [dabutaizha/juzimi#2]
我最近在学习你的项目

**Comment by dabutaizha** [comment]
项目内配置了Stetho调试框架

**Comment by dabutaizha** [comment]
项目配置过Stetho调试框架

**Comment by seeeeal** [comment]
项目引用了Stetho依赖
需要查看网络日志 可以打开Chrome浏览器 输入Chrome://inspect即可

如果需要在控制台查看日志 可以修改okHttp配置HttpLoggingInterceptor
