### ISSUE TITLE
句子迷网站维护中

### ISSUE THREAD

**Issue by einverne** [dabutaizha/juzimi#3]
您好

今天看到句子迷网站维护，就正好来搜到这个项目，我看到您项目中是直接爬取的句子迷的内容，这是不是意味着如果句子迷网站挂了，那这个应用也使用不了？不知道您那边有没有缓存句子迷的内容？

**Comment by seeeeal** [comment]
对的 由于句子迷维护该应用无法正常使用 这边没有做任何缓存

**Comment by einverne** [comment]
我个人想要做一个类似句子迷的网站，看看到时候是否合作一下 :)
